///////////////////////////////////////////////////////////////////////////////
// Untitled1Services.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_Untitled1 = 0x3F000000;
#define SRVNAME_UNTITLED1 "Untitled1"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_Untitled1CGit_CPP_Module = {0x272a57ca,0x03aa,0x4a82,{0x9b,0x4e,0x07,0x64,0x95,0x00,0x78,0x45}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_Git_CPP_ModuleParameter = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _Git_CPP_ModuleParameter
{
	ULONG data1;
	ULONG data2;
	double data3;
} Git_CPP_ModuleParameter, *PGit_CPP_ModuleParameter;

typedef struct _Git_CPP_ModuleInputs
{
	ULONG Value;
	ULONG Status;
	ULONG Data;
} Git_CPP_ModuleInputs, *PGit_CPP_ModuleInputs;

typedef struct _Git_CPP_ModuleOutputs
{
	ULONG Value;
	ULONG Control;
	ULONG Data;
} Git_CPP_ModuleOutputs, *PGit_CPP_ModuleOutputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_Git_CPP_ModuleInputs 0
#define ADI_Git_CPP_ModuleOutputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
